# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from unity_package/Simulink2MotionPC.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Simulink2MotionPC(genpy.Message):
  _md5sum = "f42ae6ddad2a7bc05f1d468d2ad4cc0f"
  _type = "unity_package/Simulink2MotionPC"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x_ddot 
float64 y_ddot
float64 z_ddot
float64 roll_ddot
float64 pitch_ddot
float64 yaw_ddot

"""
  __slots__ = ['x_ddot','y_ddot','z_ddot','roll_ddot','pitch_ddot','yaw_ddot']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_ddot,y_ddot,z_ddot,roll_ddot,pitch_ddot,yaw_ddot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Simulink2MotionPC, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x_ddot is None:
        self.x_ddot = 0.
      if self.y_ddot is None:
        self.y_ddot = 0.
      if self.z_ddot is None:
        self.z_ddot = 0.
      if self.roll_ddot is None:
        self.roll_ddot = 0.
      if self.pitch_ddot is None:
        self.pitch_ddot = 0.
      if self.yaw_ddot is None:
        self.yaw_ddot = 0.
    else:
      self.x_ddot = 0.
      self.y_ddot = 0.
      self.z_ddot = 0.
      self.roll_ddot = 0.
      self.pitch_ddot = 0.
      self.yaw_ddot = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_ddot, _x.y_ddot, _x.z_ddot, _x.roll_ddot, _x.pitch_ddot, _x.yaw_ddot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_ddot, _x.y_ddot, _x.z_ddot, _x.roll_ddot, _x.pitch_ddot, _x.yaw_ddot,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_ddot, _x.y_ddot, _x.z_ddot, _x.roll_ddot, _x.pitch_ddot, _x.yaw_ddot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_ddot, _x.y_ddot, _x.z_ddot, _x.roll_ddot, _x.pitch_ddot, _x.yaw_ddot,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
