// Generated by gencpp from file unity_package/Simulink2Arduino.msg
// DO NOT EDIT!


#ifndef UNITY_PACKAGE_MESSAGE_SIMULINK2ARDUINO_H
#define UNITY_PACKAGE_MESSAGE_SIMULINK2ARDUINO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_package
{
template <class ContainerAllocator>
struct Simulink2Arduino_
{
  typedef Simulink2Arduino_<ContainerAllocator> Type;

  Simulink2Arduino_()
    : torque_reference(0.0)  {
    }
  Simulink2Arduino_(const ContainerAllocator& _alloc)
    : torque_reference(0.0)  {
  (void)_alloc;
    }



   typedef double _torque_reference_type;
  _torque_reference_type torque_reference;




  typedef boost::shared_ptr< ::unity_package::Simulink2Arduino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_package::Simulink2Arduino_<ContainerAllocator> const> ConstPtr;

}; // struct Simulink2Arduino_

typedef ::unity_package::Simulink2Arduino_<std::allocator<void> > Simulink2Arduino;

typedef boost::shared_ptr< ::unity_package::Simulink2Arduino > Simulink2ArduinoPtr;
typedef boost::shared_ptr< ::unity_package::Simulink2Arduino const> Simulink2ArduinoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_package::Simulink2Arduino_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_package::Simulink2Arduino_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace unity_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'unity_package': ['/home/mcsim/catkin_Simulink/src/unity_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_package::Simulink2Arduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_package::Simulink2Arduino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_package::Simulink2Arduino_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b553eb5fddc8e8c8cb9caa506e3fefe4";
  }

  static const char* value(const ::unity_package::Simulink2Arduino_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb553eb5fddc8e8c8ULL;
  static const uint64_t static_value2 = 0xcb9caa506e3fefe4ULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_package/Simulink2Arduino";
  }

  static const char* value(const ::unity_package::Simulink2Arduino_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 torque_reference\n\
";
  }

  static const char* value(const ::unity_package::Simulink2Arduino_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.torque_reference);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Simulink2Arduino_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_package::Simulink2Arduino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_package::Simulink2Arduino_<ContainerAllocator>& v)
  {
    s << indent << "torque_reference: ";
    Printer<double>::stream(s, indent + "  ", v.torque_reference);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_PACKAGE_MESSAGE_SIMULINK2ARDUINO_H
